### ISSUE TITLE
两个页面之间多次跳转后会显示路由错误，无法跳转

### ISSUE THREAD

**Issue by ONEFORALL99** [yxk0909/uni-router-interceptor#2]
两个页面之间多次跳转后会显示路由错误，无法跳转

**Comment by yxk0909** [comment]
@ONEFORALL99 能否详细描述一下问题和报的什么错误

**Comment by ONEFORALL99** [comment]
![image](https://user-images.githubusercontent.com/73486635/226174763-1e54fd3a-c60f-4f64-868e-e1df4813a644.png)
![image](https://user-images.githubusercontent.com/73486635/226174782-8031f252-2040-47d4-aaec-3981733e1f73.png)
这是控制台和源码

**Comment by yxk0909** [comment]
路由跳转你是用的 `uni.navigateTo` 这种方法跳转的么？  你可以先暂时使用 `this.$Router` 进行路由跳转，这个问题我最近抽时间看一下怎么解决

**Comment by ONEFORALL99** [comment]
我使用的是this.$router.navigateTo跳转的

**Comment by yxk0909** [comment]
```javascript
router.error(error => {
   console.error(error)
})
```
使用这个打印一下错误日志，或者提供一个简易的 demo，我具体看一下是啥问题

**Comment by ONEFORALL99** [comment]
![image](https://user-images.githubusercontent.com/73486635/226333743-e623898d-8461-401e-b6be-72d851faaa13.png)

**Comment by yxk0909** [comment]
小程序端的么，问题已收到，我瞅瞅

**Comment by ONEFORALL99** [comment]
对，使用的是Hbuilder，在微信开发者工具上运行的
