### ISSUE TITLE
{"errMsg":"switchTab:fail Missing required parameter `url`"}

### ISSUE THREAD

**Issue by hubeishuaige** [yxk0909/uni-router-interceptor#3]
#### 版本号
2.0.1

#### UNI编译的平台
Android 

#### 问题描述
在tabbar页面跳转的时候，报错：{"errMsg":"switchTab:fail Missing required parameter `url`"}，我是完全按照demo做的，不知道为什么，
![image](https://github.com/yxk0909/uni-router-interceptor/assets/21007762/b9481e42-a844-48ba-ab01-b89792b39396)

**Comment by yxk0909** [comment]
@hubeishuaige 看着报错是缺少 'url' 参数，看看是否漏传了 url，另外 switchTab 是不能携带 query 参数的
